server:
  port: 9092

mybatis:
  mapper-locations: classpath:/mapper/*.xml

route-data-source:
  default-data-source: ygg_sale_platform:master:1
  data-source-list:
    -
      name: db_test
      masterPatterns:
        - execution(* com.hy.dynamicdatasource.mapper..*.insert*(..))
      slavePatterns:
        - execution(* com.hy.dynamicdatasource.mapper..*.select*(..))
      masters:
        -
          weight: 1
          index: 1
          data-source:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://172.16.52.128:3306/db_test?useUnicode=true&amp;characterEncoding=UTF8&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true
            username: root
            password:
            initial-size: 3
            min-idle: 3
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat
      salves:
        -
          weight: 1
          index: 1
          data-source:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://172.16.52.128:3306/db_test_slave?useUnicode=true&amp;characterEncoding=UTF8&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true
            username: root
            password:
            initial-size: 3
            min-idle: 3
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat
